services:
  postgres:
    ports:
      - "5432:5432"
  sounddock:
    image: sounddock:local
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      SD_COOKIE_SECURE: "false"
      SD_PUBLIC_URL: http://localhost:8080
      SD_LOG_LEVEL: debug
  discord-worker:
    image: sounddock:local

