ALTER TABLE backups ADD COLUMN IF NOT EXISTS destination TEXT NOT NULL DEFAULT 'local';
ALTER TABLE backups ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'sql';
ALTER TABLE backups ADD COLUMN IF NOT EXISTS remote_key TEXT NOT NULL DEFAULT '';
